### ISSUE TITLE
add to pool during runtiime

### ISSUE THREAD

**Issue by p0ntsNL** [eerimoq/asyncbg#1]
Would it be possible to add more background tasks over the time this is running?

For example I have a foreground job that is looking for trade opportunaties in a crypto market, whenever it sees one it will initiate a background tasks which runs until complete but should not block the others.

- Can I initiate more background tasks from the foreground task? 
- Can the foreground tasks stay in a while loop so that it never stops?

so:

- start foreground task in while loop (keeps checking for new trades)
- if found, start background tasks that does not block other tasks

thanks in advance.

**Comment by bluenara** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "<string>", line 1, in <module>
    exitcode = _main(fd, parent_sentinel)
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
  File "<string>", line 1, in <module>
    exec(code, run_globals)
    prepare(preparation_data)
Traceback (most recent call last):
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "D:\my\py\stock\z.py", line 23, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    exitcode = _main(fd, parent_sentinel)
    asyncio.run(main())
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    prepare(preparation_data)
    return loop.run_until_complete(main)
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    return future.result()
    return _run_module_code(code, init_globals, run_name,
    _fixup_main_from_path(data['init_main_from_path'])
    return _run_module_code(code, init_globals, run_name,
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\my\py\stock\z.py", line 20, in main
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    result = await asyncbg.call(work, 4, 5)
    _run_code(code, mod_globals, init_globals,
    main_content = runpy.run_path(main_path,
    _run_code(code, mod_globals, init_globals,
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
    exec(code, run_globals)
    return _run_module_code(code, init_globals, run_name,
    exec(code, run_globals)
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
  File "D:\my\py\stock\z.py", line 23, in <module>
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
  File "D:\my\py\stock\z.py", line 23, in <module>
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    self._start_queue_management_thread()
    asyncio.run(main())
    _run_code(code, mod_globals, init_globals,
    asyncio.run(main())
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    self._adjust_process_count()
    return loop.run_until_complete(main)
    exec(code, run_globals)
    return loop.run_until_complete(main)
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 608, in _adjust_process_count
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
  File "D:\my\py\stock\z.py", line 23, in <module>
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
  File "D:\my\py\stock\z.py", line 23, in <module>
    p.start()
    return future.result()
    asyncio.run(main())
    return future.result()
    asyncio.run(main())
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
  File "D:\my\py\stock\z.py", line 20, in main
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
  File "D:\my\py\stock\z.py", line 20, in main
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
    self._popen = self._Popen(self)
    result = await asyncbg.call(work, 4, 5)
    return loop.run_until_complete(main)
    result = await asyncbg.call(work, 4, 5)
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
Traceback (most recent call last):
    return Popen(process_obj)
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
    return future.result()
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
    return future.result()
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
  File "D:\my\py\stock\z.py", line 20, in main
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
  File "D:\my\py\stock\z.py", line 20, in main
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    prep_data = spawn.get_preparation_data(process_obj._name)
    self._start_queue_management_thread()
    result = await asyncbg.call(work, 4, 5)
    self._start_queue_management_thread()
    result = await asyncbg.call(work, 4, 5)
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    _check_not_importing_main()
    self._adjust_process_count()
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
    self._adjust_process_count()
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 608, in _adjust_process_count
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 608, in _adjust_process_count
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    raise RuntimeError('''
    p.start()
    self._start_queue_management_thread()
    p.start()
    self._start_queue_management_thread()
    _fixup_main_from_path(data['init_main_from_path'])
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path

    self._popen = self._Popen(self)
    self._adjust_process_count()
    self._popen = self._Popen(self)
    self._adjust_process_count()
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 608, in _adjust_process_count
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 608, in _adjust_process_count
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 265, in run_path
    return Popen(process_obj)
    p.start()
    return Popen(process_obj)
    p.start()
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 121, in start
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    prep_data = spawn.get_preparation_data(process_obj._name)
    self._popen = self._Popen(self)
    prep_data = spawn.get_preparation_data(process_obj._name)
    self._popen = self._Popen(self)
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 326, in _Popen
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    _check_not_importing_main()
    return Popen(process_obj)
    _check_not_importing_main()
    return Popen(process_obj)
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "D:\my\py\stock\z.py", line 23, in <module>
    raise RuntimeError('''
    prep_data = spawn.get_preparation_data(process_obj._name)
    raise RuntimeError('''
    prep_data = spawn.get_preparation_data(process_obj._name)
    asyncio.run(main())
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run

    _check_not_importing_main()

    _check_not_importing_main()
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    raise RuntimeError('''
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    return future.result()
  File "D:\my\py\stock\z.py", line 20, in main
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    result = await asyncbg.call(work, 4, 5)
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 645, in submit
    self._start_queue_management_thread()
  File "D:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 584, in _start_queue_management_thread
Traceback (most recent call last):
  File "z.py", line 23, in <module>
    asyncio.run(main())
  File "D:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "z.py", line 20, in main
    result = await asyncbg.call(work, 4, 5)
  File "D:\ProgramData\Anaconda3\lib\site-packages\asyncbg\__init__.py", line 33, in call
    return await asyncio.wrap_future(self.submit(callback, *args, **kwargs))
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
